"""Beschreibungen und Metadaten für Spieler-Metriken.

Dieses Modul spiegelt die Struktur aus ``teams.labels`` wider, ist jedoch auf
Spieler-Daten zugeschnitten.  Die Konstanten werden zunächst lediglich
vorbereitet und noch nicht aktiv im Players-Dashboard verwendet.
"""

from __future__ import annotations

import re

__all__ = [
    "norm_comp_key",
    "COLUMN_LABELS",
    "METRIC_CATEGORIES",
    "CATEGORY_LABELS",
    "METRIC_NICHT",
    "PLAYER_INFO_FIELDS",
    "PLAYER_NICHT",
    "COMPETITION_LABELS",
]


def norm_comp_key(value: str | None) -> str:
    """Normalize competition names for robust lookups."""
    if not value:
        return ""
    value = value.strip()
    value = re.sub(r"[\u2019\u2018`´']+", "'", value)
    value = re.sub(r"\s*'\s*", "'", value)
    value = re.sub(r"\s+", " ", value)
    return value.casefold()


COMPETITION_LABELS: dict[str, str] = {
    "Eredivisie": "Eredivisie, NLD 1",
    "Ligue 2": "Ligue 2, FR 2",
    "Ekstraklasa": "Ekstraklasa, POL 1",
    "La Liga 2": "La Liga 2, ESP 2",
    "Jupiler Pro League": "Jupiler Pro League, BEL 1",
    "Bundesliga": "Bundesliga, AUT 1",
    "Eerste Divisie": "Erste Divisie, NLD 2",
    "Allsvenskan": "Allsvenskan, SWE 1",
    "Czech Liga": "Czech Liga, CZE 1",
    "Superliga": "Superliga, DNK 1",
    "1. HNL": "1. HNL, HVR 1",
    "Super League": "Super League, CHE 1",
    "Eliteserien": "Eliteserien, NOR 1",
    "A-League": "A-League, AUS 1",
    "J1 League": "J1 League, JNP 1",
    "K League 1": "K League 1, KOR 1",
    "Super Liga": "Super Liga, SVK 1",
    "Championnat National": "Championnat National, FR 3",
    "Challenge League": "Challenge League, CHE 2",
    "PSL": "PSL, ZAF 1",
    "1. Division": "1. Division, DNK 2",
    "Segunda Liga": "Segunda Liga, PRT 2",
    "Challenger Pro League": "Challenger Pro League, BEL 2",
    "ligat ha'al": "Ligat Ha'Al, ISR 1",
    "2. Liga": "2. Liga, AUT 2",
    "1. SNL": "1. SNL, SVN 1",
}


COLUMN_LABELS: dict[str, tuple[str, str | None, str]] = {
    # Übersicht & Minuten
    "minutes": ("Spielminuten", "Gesamte Einsatzzeit in Minuten", "int"),
    "ninety_plus": ("90er", "Absolvierte 90-Minuten-Äquivalente", "float"),
    "games": ("Einsätze", "Anzahl der Spiele mit Einsatz", "int"),
    "games_started": ("Startelf", "Anzahl der Startelfeinsätze", "int"),
    "games_subbed_on": ("Einwechslungen", "Anzahl der Einwechslungen", "int"),
    "games_subbed_off": ("Auswechslungen", "Anzahl der Auswechslungen", "int"),
    "most_recent_match": ("Letztes Spiel", "ID des jüngsten Einsatzes", "int"),

    # Scoring & Produktion

    "goals": ("Tore", None, "int"),
    "assists": ("Vorlagen", None, "int"),
    "goal_contributions": ("Scorerpunkte", "Tore + Vorlagen", "int"),
    "goals_90": ("Tore /90", "Tore pro 90 Minuten", "float"),
    "assists_90": ("Vorlagen /90", "Vorlagen pro 90 Minuten", "float"),
    "g_a_90": ("Tore+Vorlagen /90", "Scorerpunkte pro 90 Minuten", "float"),
    "npg": ("Tore oE", "Erzielte Tore ohne Elfmeter", "int"),
    "npg_90": ("Tore oE /90", "Non-Penalty Goals pro 90 Minuten", "float"),
    "penalty_goals": ("Elfmetertore", None, "int"),
    "penalties_taken": ("Elfmeterversuche", None, "int"),
    "penalty_conversion_pct": ("Elfmeterquote", "Trefferquote bei Elfmetern", "percent"),
    "shots_total": ("Schüsse", None, "int"),
    "shots_on_target": ("Schüsse aufs Tor", None, "int"),
    "shots_on_target_pct": ("Schussgenauigkeit", "Anteil der Schüsse aufs Tor", "percent"),
    "shots_90": ("Schüsse /90", "Schüsse pro 90 Minuten", "float"),
    "shots_on_target_90": ("Schüsse aufs Tor /90", "Schüsse aufs Tor pro 90 Minuten", "float"),
    "shots_key_passes_90": ("Schüsse+Key Passes /90", "Schüsse plus Key Passes pro 90 Minuten", "float"),
    "np_shots": ("Schüsse oE", "Abgegebene Schüsse ohne Elfmeter", "int"),
    "np_xg": ("xG oE", "Erwartete Tore ohne Elfmeter", "float"),
    "np_xg_per_shot": ("xG pro Schuss oE", "Durchschnittliche xG pro Schuss ohne Elfmeter", "float"),
    "np_xg_90": ("xG oE /90", "Non-Penalty xG pro 90 Minuten", "float"),
    "npxgxa": ("xG+xA oE", "Non-Penalty xG plus xA", "float"),
    "npxgxa_90": ("xG+xA oE /90", "Non-Penalty xG+xA pro 90 Minuten", "float"),
    "npxg": ("xG oE", "Erwartete Tore ohne Elfmeter", "float"),
    "npxg_90": ("xG oE /90", "Non-Penalty xG pro 90 Minuten", "float"),
    "xg": ("xG", "Erwartete Tore inklusive Elfmeter", "float"),
    "xg_90": ("xG /90", "xG pro 90 Minuten", "float"),
    "xgchain": ("xGChain", "xGChain – Torbeteiligung in der Ballzirkulation", "float"),
    "xgchain_90": ("xGChain /90", "xGChain pro 90 Minuten", "float"),
    "xgbuildup": ("xGBuildup", "xGBuildup – xG aus Aufbau-Aktionen ohne Schüsse/Assists", "float"),
    "xgbuildup_90": ("xGBuildup /90", "xGBuildup pro 90 Minuten", "float"),
    "xa": ("xA", "Expected Assists", "float"),
    "xa_90": ("xA /90", "Expected Assists pro 90 Minuten", "float"),
    "key_passes": ("Key Passes", "Vorlagen zu einem Schuss", "int"),
    "key_passes_90": ("Key Passes /90", "Key Pässe pro 90 Minuten", "float"),
    "shot_assists": ("Shot Assists", "Pässe die zu einem Abschluss führen", "int"),
    "assisted_shots": ("Vorlagen zu Schüssen", "Anzahl der von diesem Spieler vorbereiteten Schüsse", "int"),

    # Passspiel
    "passes_completed": ("Pässe erfolgreich", "Beim Mitspieler angekommene Pässe", "int"),
    "passes_attempted": ("Pässe gesamt", "Versuchte Pässe", "int"),
    "pass_completion_pct": ("Passquote", "Erfolgreiche Pässe / Versuche", "percent"),
    "passes_completed_short": ("Pässe kurz", "Erfolgreiche kurze Pässe (0-15m)", "int"),
    "passes_attempted_short": ("Pässe kurz Versuche", "Versuchte kurze Pässe (0-15m)", "int"),
    "pass_completion_pct_short": ("Passquote kurz", "Quote erfolgreicher kurzer Pässe", "percent"),
    "passes_completed_medium": ("Pässe mittel", "Erfolgreiche mittlere Pässe (15-30m)", "int"),
    "passes_attempted_medium": ("Pässe mittel Versuche", "Versuchte mittlere Pässe (15-30m)", "int"),
    "pass_completion_pct_medium": ("Passquote mittel", "Quote erfolgreicher mittlerer Pässe", "percent"),
    "passes_completed_long": ("Pässe lang", "Erfolgreiche lange Pässe (30m+)", "int"),
    "passes_attempted_long": ("Pässe lang Versuche", "Versuchte lange Pässe (30m+)", "int"),
    "pass_completion_pct_long": ("Passquote lang", "Quote erfolgreicher langer Pässe", "percent"),
    "progressive_passes": ("Progressive Pässe", "Vorwärtsgerichtete Pässe mit deutlichem Raumgewinn", "int"),
    "progressive_passes_90": ("Progressive Pässe /90", "Progressive Pässe pro 90 Minuten", "float"),
    "passes_into_final_third": ("Pässe ins letzte Drittel", None, "int"),
    "passes_into_penalty_area": ("Pässe in den Strafraum", None, "int"),
    "switches": ("Seitenverlagerungen", "Lange Diagonalbälle (40m+)", "int"),
    "through_balls": ("Steilpässe", "Durchgesteckte Pässe hinter die Abwehr", "int"),
    "crosses": ("Flanken", None, "int"),
    "crosses_into_penalty_area": ("Flanken in den Strafraum", None, "int"),
    "deep_completions": ("Deep Completions", "Erfolgreiche Zuspiele nahe des Tores", "int"),
    "progressive_passes_received": ("Fortschrittliche Anspiele", "Pässe, die den Spieler deutlich voranbringen", "int"),
    "passes_received": ("Erhaltene Pässe", None, "int"),
    
    # Ballbesitz & Dribbling
    "touches": ("Ballkontakte", None, "int"),
    "touches_def_pen_area": ("Kontakte eigener 16er", None, "int"),
    "touches_mid_3rd": ("Kontakte Mittelfeld", "Ballkontakte im mittleren Drittel", "int"),
    "touches_att_pen_area": ("Kontakte Strafraum", "Ballkontakte im gegnerischen Strafraum", "int"),
    "touches_att_3rd": ("Kontakte Offensivdrittel", None, "int"),
    "carries": ("Carries", "Ballführungen mit Kontrolle", "int"),
    "carries_90": ("Carries /90", "Carries pro 90 Minuten", "float"),
    "progressive_carries": ("Progressive Carries", "Ballführungen mit Raumgewinn", "int"),
    "progressive_carries_90": ("Progressive Carries /90", "Progressive Carries pro 90 Minuten", "float"),
    "carries_into_final_third": ("Carries ins letzte Drittel", None, "int"),
    "carries_into_penalty_area": ("Carries in den Strafraum", None, "int"),
    "carry_progressive_distance": ("Carry-Distanz vorwärts", "Meter Vorwärtsbewegung mit Ball", "float"),
    "carry_total_distance": ("Carry-Distanz gesamt", None, "float"),
    "take_ons": ("Dribblings", "Versuchte 1-gegen-1", "int"),
    "take_ons_won": ("Dribblings gewonnen", None, "int"),
    "take_on_success_pct": ("Dribbelquote", "Erfolgsquote bei Take-Ons", "percent"),
    "successful_dribbles": ("Erfolgreiche Dribblings", None, "int"),
    "failed_dribbles": ("Misslungene Dribblings", None, "int"),
    "dribble_ratio": ("Dribbling-Erfolgsquote", "Erfolgreiche Dribblings / Versuche", "percent"),
    "nutmegs": ("Beinschüsse", None, "int"),
    "miscontrols": ("Unsichere Annahmen", "Ballverluste bei Ballannahme", "int"),
    "dispossessed": ("Ballverluste", "Verluste unter Druck", "int"),
    # Defensivarbeit
    "pressures": ("Pressures", "Anläufe auf den Ballführenden", "int"),
    "padj_pressures_90": ("Pressures (adj.) /90", "An Intensität angepasste Pressures pro 90", "float"),
    "pressure_regains": ("Pressure-Gewinne", "Ballgewinne innerhalb 5s nach Pressure", "int"),
    "pressure_regain_pct": ("Pressure-Erfolgsquote", "Anteil erfolgreicher Pressures", "percent"),
    "counterpressures": ("Gegenpressing", "Pressures innerhalb 5s nach Ballverlust", "int"),
    "counterpressure_regains": ("Gegenpressing-Gewinne", "Ballgewinne nach Gegenpressing", "int"),
    "counterpressure_regain_pct": ("Gegenpressing Quote", "Erfolgsquote Gegenpressing", "percent"),
    "tackles": ("Zweikämpfe am Ball", "Versuchte Tacklings", "int"),
    "tackles_won": ("Tacklings gewonnen", None, "int"),
    "tackle_success_pct": ("Tacklingquote", "Erfolgsquote bei Tacklings", "percent"),
    "tackles_def_3rd": ("Tackles Defensivdrittel", None, "int"),
    "tackles_mid_3rd": ("Tackles Mittelfeld", None, "int"),
    "tackles_att_3rd": ("Tackles Offensivdrittel", None, "int"),
    "interceptions": ("Interceptions", "Abgefangene Zuspiele", "int"),
    "blocks": ("Blocks", "Geblockte Schüsse/Pässe", "int"),
    "clearances": ("Klärungsaktionen", None, "int"),
    "recoveries": ("Ballgewinne", "Lose Bälle kontrolliert aufgenommen", "int"),
    "duels": ("Zweikämpfe", None, "int"),
    "duels_won": ("Zweikämpfe gewonnen", None, "int"),
    "duel_win_pct": ("Zweikampfquote", "Gewonnene Zweikämpfe in %", "percent"),
    "aerials_won": ("Luftzweikämpfe gewonnen", None, "int"),
    "aerials_lost": ("Luftzweikämpfe verloren", None, "int"),
    "aerial_win_pct": ("Luftzweikampfquote", "Gewonnene Luftduelle in %", "percent"),
    "fouls_committed": ("Fouls begangen", None, "int"),
    "fouls_won": ("Fouls gezogen", None, "int"),
    "yellow_cards": ("Gelbe Karten", None, "int"),
    "second_yellow_cards": ("Gelb-Rot", None, "int"),
    "red_cards": ("Rote Karten", None, "int"),
    "own_goals": ("Eigentore", None, "int"),
    # Torwart-spezifische Werte
    "gk_shots_on_target_against": ("Schüsse aufs Tor gegen", None, "int"),
    "gk_goals_against": ("Gegentore", None, "int"),
    "gk_saves": ("Paraden", None, "int"),
    "gk_save_pct": ("Paradenquote", "Anteil gehaltener Schüsse aufs Tor", "percent"),
    "gk_psxg": ("Post-Shot xG", "Erwartete Gegentore basierend auf Schussqualität", "float"),
    "gk_psxg_diff": ("PSxG +/-", "Paraden im Vergleich zu erwarteten Gegentoren", "float"),
    "gk_crosses_stopped": ("Gefangene Flanken", None, "int"),
    "gk_crosses_stopped_pct": ("Flankenquote", "Anteil gehaltener Flanken", "percent"),
    "gk_sweeper_actions": ("Sweeper-Aktionen", "Aktionen außerhalb des Strafraums", "int"),
    "gk_avg_sweeper_distance": ("Sweeper-Distanz", "Ø Distanz der Sweeper-Aktionen", "float"),
    "gk_passes_completed": ("GK-Pässe erfolgreich", None, "int"),
    "gk_passes_attempted": ("GK-Pässe gesamt", None, "int"),
    "gk_pass_completion_pct": ("GK-Passquote", None, "percent"),
    "gk_passes_launched": ("GK-Lange Pässe", "Vom Torwart gestartete lange Pässe", "int"),
    "gk_passes_launched_pct": ("GK-Langpassquote", "Anteil langer Pässe", "percent"),
    "gk_avg_pass_length": ("GK-Passlänge", "Durchschnittliche Länge der Torwartpässe", "float"),
}


METRIC_CATEGORIES: dict[str, list[str]] = {
    "overview": [
        "minutes",
        "ninety_plus",
        "games",
        "games_started",
        "games_subbed_on",
        "games_subbed_off",
        "goals",
        "assists",
        "goal_contributions",
        "goals_90",
        "assists_90",
        "g_a_90",
        "npg",
        "npg_90",
        "npxg",
        "npxg_90",
        "npxgxa",
        "npxgxa_90",
    ],
    "shooting": [
        "shots_total",
        "shots_on_target",
        "shots_on_target_pct",
        "shots_90",
        "shots_on_target_90",
        "np_shots",
        "np_xg",
        "np_xg_per_shot",
        "np_xg_90",
        "xg",
        "xg_90",
        "xgchain",
        "xgchain_90",
        "xgbuildup",
        "xgbuildup_90",
        "xa",
        "xa_90",
        "key_passes",
        "key_passes_90",
        "shots_key_passes_90",
    ],
    "passing": [
        "passes_completed",
        "passes_attempted",
        "pass_completion_pct",
        "passes_completed_short",
        "passes_attempted_short",
        "pass_completion_pct_short",
        "passes_completed_medium",
        "passes_attempted_medium",
        "pass_completion_pct_medium",
        "passes_completed_long",
        "passes_attempted_long",
        "pass_completion_pct_long",
        "progressive_passes",
        "progressive_passes_90",
        "passes_into_final_third",
        "passes_into_penalty_area",
        "switches",
        "through_balls",
        "crosses",
        "crosses_into_penalty_area",
        "deep_completions",
        "assisted_shots",
        "shot_assists",
    ],
    "possession": [
        "touches",
        "touches_def_pen_area",
        "touches_mid_3rd",
        "touches_att_3rd",
        "touches_att_pen_area",
        "carries",
        "carries_90",
        "progressive_carries",
        "progressive_carries_90",
        "carries_into_final_third",
        "carries_into_penalty_area",
        "carry_total_distance",
        "carry_progressive_distance",
        "passes_received",
        "progressive_passes_received",
        "miscontrols",
        "dispossessed",
    ],
    "dribbling": [
        "take_ons",
        "take_ons_won",
        "take_on_success_pct",
        "successful_dribbles",
        "failed_dribbles",
        "dribble_ratio",
        "nutmegs",
    ],
    "defending": [
        "pressures",
        "padj_pressures_90",
        "pressure_regains",
        "pressure_regain_pct",
        "counterpressures",
        "counterpressure_regains",
        "counterpressure_regain_pct",
        "tackles",
        "tackles_won",
        "tackle_success_pct",
        "tackles_def_3rd",
        "tackles_mid_3rd",
        "tackles_att_3rd",
        "interceptions",
        "blocks",
        "clearances",
        "recoveries",
        "duels",
        "duels_won",
        "duel_win_pct",
        "aerials_won",
        "aerials_lost",
        "aerial_win_pct",
        "fouls_committed",
        "fouls_won",
        "yellow_cards",
        "second_yellow_cards",
        "red_cards",
        "own_goals",
    ],
    "goalkeeping": [
        "gk_shots_on_target_against",
        "gk_goals_against",
        "gk_saves",
        "gk_save_pct",
        "gk_psxg",
        "gk_psxg_diff",
        "gk_crosses_stopped",
        "gk_crosses_stopped_pct",
        "gk_sweeper_actions",
        "gk_avg_sweeper_distance",
        "gk_passes_completed",
        "gk_passes_attempted",
        "gk_pass_completion_pct",
        "gk_passes_launched",
        "gk_passes_launched_pct",
        "gk_avg_pass_length",
    ],
    "discipline": [
        "fouls_committed",
        "fouls_won",
        "yellow_cards",
        "second_yellow_cards",
        "red_cards",
    ],
}


CATEGORY_LABELS: dict[str, str] = {
    "overview": "Überblick",
    "shooting": "Torabschluss & Kreation",
    "passing": "Passspiel",
    "possession": "Ballbesitz & Ballführung",
    "dribbling": "Dribblings",
    "defending": "Defensive Aktionen",
    "goalkeeping": "Torhüter",
    "discipline": "Disziplin",
}


METRIC_NICHT: dict[str, tuple[str | None, str | None, str | None]] = {
    "player_id": ("Spieler-ID", "Eindeutige Kennung des Spielers", "int"),
    "team_id": ("Team-ID", "Eindeutige Kennung des Teams", "int"),
    "competition_id": ("Liga-ID", "Eindeutige Kennung des Wettbewerbs", "int"),
    "season_id": ("Saison-ID", "Eindeutige Kennung der Saison", "int"),
    "season_name": ("Saison", None, "string"),
    "team_name": ("Team", None, "string"),
    "competition_name": ("Wettbewerb", None, "string"),
    "player_name": ("Spieler", None, "string"),
    "primary_position": ("Hauptposition", None, "string"),
    "secondary_position": ("Nebenposition", None, "string"),
    "birth_date": ("Geburtsdatum", None, "date"),
    "height": ("Größe", "Körpergröße in cm", "float"),
    "weight": ("Gewicht", "Gewicht in kg", "float"),
    "player_female": ("Frauen-Team", "True, wenn die Spielerin einem Frauen-Team angehört", "bool"),
}


PLAYER_INFO_FIELDS: list[str] = [
    "player_name",
    "team_name",
    "competition_name",
    "season_name",
    "birth_date",
    "weight",
    "height",
    "primary_position",
    "secondary_position",
    "minutes",
    "ninety_plus",
    "games",
    "games_started",
]


PLAYER_NICHT: dict[str, tuple[str, str | None, str]] = {
    "match_id": ("Match-ID", "Eindeutige Kennung des Spiels", "int"),
    "match_date": ("Spieltermin", None, "date"),
    "opponent_team_id": ("Gegner-ID", None, "int"),
    "opponent_team_name": ("Gegner", None, "string"),
    "player_shirt_number": ("Rückennummer", None, "int"),
}
